-- MySQL Script generated by MySQL Workbench
-- Thu Mar 23 19:29:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estabelecimento` (
  `PK_idEstab` INT NOT NULL,
  `Nome` VARCHAR(255) NULL,
  `Local` VARCHAR(255) NULL,
  `CEP` INT(7) NULL,
  PRIMARY KEY (`PK_idEstab`),
  UNIQUE INDEX `PK_idEstab_UNIQUE` (`PK_idEstab` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `PK_idEst` INT NOT NULL,
  `FK_idEstab` INT NOT NULL,
  `Espaço` VARCHAR(255) NULL,
  `Quantidade` INT NULL,
  `Data_Entrada` DATETIME NULL,
  `Data_Saida` DATETIME NULL,
  PRIMARY KEY (`PK_idEst`),
  INDEX `fk_Estoque_Estabelecimento1_idx` (`FK_idEstab` ASC) VISIBLE,
  UNIQUE INDEX `PK_idEst_UNIQUE` (`PK_idEst` ASC) VISIBLE,
  UNIQUE INDEX `FK_idEstab_UNIQUE` (`FK_idEstab` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Estabelecimento1`
    FOREIGN KEY (`FK_idEstab`)
    REFERENCES `mydb`.`Estabelecimento` (`PK_idEstab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `PK_idProd` INT NOT NULL,
  `FK_idEst` INT NOT NULL,
  `Tipo` VARCHAR(255) NULL,
  `Nome` VARCHAR(255) NULL,
  `Lote` CHAR(5) NULL,
  `Validade` DATE NULL,
  `Valor_Unitario` DECIMAL(10,2) NULL,
  PRIMARY KEY (`PK_idProd`, `FK_idEst`),
  INDEX `fk_Produtos_Estoque1_idx` (`FK_idEst` ASC) VISIBLE,
  UNIQUE INDEX `PK_idProd_UNIQUE` (`PK_idProd` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Estoque1`
    FOREIGN KEY (`FK_idEst`)
    REFERENCES `mydb`.`Estoque` (`PK_idEst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `PK_idForn` INT NOT NULL,
  `FK_idEst` INT NOT NULL,
  `CNPJ` INT(11) NULL,
  `CPF` INT(9) NULL,
  `Nome` VARCHAR(255) NULL,
  `Ender` VARCHAR(255) NULL,
  `Ativo` CHAR(2) NULL,
  PRIMARY KEY (`PK_idForn`, `FK_idEst`),
  INDEX `fk_Fornecedor_Estoque1_idx` (`FK_idEst` ASC) VISIBLE,
  UNIQUE INDEX `PK_idForn_UNIQUE` (`PK_idForn` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_Estoque1`
    FOREIGN KEY (`FK_idEst`)
    REFERENCES `mydb`.`Estoque` (`PK_idEst`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `PK_idClient` INT NOT NULL,
  `CPF` INT(9) NULL,
  `Nome` VARCHAR(255) NULL,
  `Data_Nascimento` DATE NULL,
  `Ativo` CHAR(2) NULL,
  PRIMARY KEY (`PK_idClient`),
  UNIQUE INDEX `PK_idClient_UNIQUE` (`PK_idClient` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `PK_idPed` INT NOT NULL,
  `FK_idClient` INT NOT NULL,
  PRIMARY KEY (`PK_idPed`, `FK_idClient`),
  INDEX `fk_Pedido_Cliente1_idx` (`FK_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`FK_idClient`)
    REFERENCES `mydb`.`Cliente` (`PK_idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Itens_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Itens_Pedido` (
  `FK_idPed` INT NOT NULL,
  `FK_idProd` INT NOT NULL,
  `Nome` VARCHAR(255) NULL,
  `Quantidade` DOUBLE(10,2) NULL,
  `Valor_Total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`FK_idPed`, `FK_idProd`),
  INDEX `fk_Pedido_has_Produtos_Produtos1_idx` (`FK_idProd` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produtos_Pedido1_idx` (`FK_idPed` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produtos_Pedido1`
    FOREIGN KEY (`FK_idPed`)
    REFERENCES `mydb`.`Pedido` (`PK_idPed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produtos_Produtos1`
    FOREIGN KEY (`FK_idProd`)
    REFERENCES `mydb`.`Produtos` (`PK_idProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forma_Pag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Forma_Pag` (
  `idFormaPag` INT NOT NULL,
  `Nome` VARCHAR(255) NULL,
  `Status` CHAR(2) NULL,
  PRIMARY KEY (`idFormaPag`),
  UNIQUE INDEX `idForma_Pag_UNIQUE` (`idFormaPag` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nota_Fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nota_Fiscal` (
  `idNotaFiscal` INT NOT NULL,
  `FK_idPed` INT NOT NULL,
  `FK_idClient` INT NOT NULL,
  `FK_idFormaPag` INT NOT NULL,
  `Data` TIMESTAMP NULL,
  PRIMARY KEY (`idNotaFiscal`, `FK_idPed`, `FK_idClient`, `FK_idFormaPag`),
  INDEX `fk_Nota_Fiscal_Pedido1_idx` (`FK_idPed` ASC, `FK_idClient` ASC) VISIBLE,
  INDEX `fk_Nota_Fiscal_Forma_Pag1_idx` (`FK_idFormaPag` ASC) VISIBLE,
  UNIQUE INDEX `FK_idFormaPag_UNIQUE` (`FK_idFormaPag` ASC) VISIBLE,
  UNIQUE INDEX `FK_idClient_UNIQUE` (`FK_idClient` ASC) VISIBLE,
  UNIQUE INDEX `idNotaFiscal_UNIQUE` (`idNotaFiscal` ASC) VISIBLE,
  UNIQUE INDEX `FK_idPed_UNIQUE` (`FK_idPed` ASC) VISIBLE,
  CONSTRAINT `fk_Nota_Fiscal_Pedido1`
    FOREIGN KEY (`FK_idPed` , `FK_idClient`)
    REFERENCES `mydb`.`Pedido` (`PK_idPed` , `FK_idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nota_Fiscal_Forma_Pag1`
    FOREIGN KEY (`FK_idFormaPag`)
    REFERENCES `mydb`.`Forma_Pag` (`idFormaPag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `FK_idEstab` INT NOT NULL,
  `CPF` INT(9) NULL,
  `Nome` VARCHAR(255) NULL,
  `Telefone` INT(11) NULL,
  PRIMARY KEY (`idFuncionario`, `FK_idEstab`),
  INDEX `fk_Vendedor_Estabelecimento1_idx` (`FK_idEstab` ASC) VISIBLE,
  UNIQUE INDEX `idVendedor_UNIQUE` (`idFuncionario` ASC) VISIBLE,
  UNIQUE INDEX `FK_idEstab_UNIQUE` (`FK_idEstab` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Vendedor_Estabelecimento1`
    FOREIGN KEY (`FK_idEstab`)
    REFERENCES `mydb`.`Estabelecimento` (`PK_idEstab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Setor` (
  `idSetor` INT NOT NULL,
  `Setor` VARCHAR(45) NULL,
  `FK_idEstab` INT NOT NULL,
  `FK_idFuncionario` INT NOT NULL,
  `Nome` VARCHAR(255) NULL,
  `Operação` VARCHAR(255) NULL,
  `Ativo` CHAR(2) NULL,
  PRIMARY KEY (`idSetor`),
  INDEX `fk_Setor_Vendedor1_idx` (`FK_idFuncionario` ASC, `FK_idEstab` ASC) VISIBLE,
  UNIQUE INDEX `FK_idEstab_UNIQUE` (`FK_idEstab` ASC) VISIBLE,
  UNIQUE INDEX `idSetor_UNIQUE` (`idSetor` ASC) VISIBLE,
  CONSTRAINT `fk_Setor_Vendedor1`
    FOREIGN KEY (`FK_idFuncionario` , `FK_idEstab`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario` , `FK_idEstab`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caixa` (
  `idCaixa` INT NOT NULL,
  `FK_idFormaPag` INT NOT NULL,
  `Date` TIMESTAMP NULL,
  `Status_Pag` CHAR(2) NULL,
  PRIMARY KEY (`idCaixa`),
  UNIQUE INDEX `idCaixa_UNIQUE` (`idCaixa` ASC) VISIBLE,
  INDEX `fk_Caixa_Forma_Pag1_idx` (`FK_idFormaPag` ASC) VISIBLE,
  UNIQUE INDEX `FK_idFormaPag_UNIQUE` (`FK_idFormaPag` ASC) VISIBLE,
  CONSTRAINT `fk_Caixa_Forma_Pag1`
    FOREIGN KEY (`FK_idFormaPag`)
    REFERENCES `mydb`.`Forma_Pag` (`idFormaPag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comissão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comissão` (
  `idComissão` INT NOT NULL,
  `FK_idSetor` INT NOT NULL,
  `FK_idCaixa` INT NOT NULL,
  `Porcentagem` FLOAT(10,2) NULL,
  UNIQUE INDEX `idComissão_UNIQUE` (`idComissão` ASC) VISIBLE,
  PRIMARY KEY (`FK_idSetor`, `FK_idCaixa`),
  UNIQUE INDEX `FK_idSetor_UNIQUE` (`FK_idSetor` ASC) VISIBLE,
  INDEX `fk_Comissão_Caixa1_idx` (`FK_idCaixa` ASC) VISIBLE,
  UNIQUE INDEX `FK_idCaixa_UNIQUE` (`FK_idCaixa` ASC) VISIBLE,
  CONSTRAINT `fk_Comissão_Setor1`
    FOREIGN KEY (`FK_idSetor`)
    REFERENCES `mydb`.`Setor` (`idSetor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comissão_Caixa1`
    FOREIGN KEY (`FK_idCaixa`)
    REFERENCES `mydb`.`Caixa` (`idCaixa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
